name: Exemplo CI/CD OK

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Mensagem inicial
        run: echo "Iniciando workflow 🚀"

      - name: Simular build
        run: echo "Build OK ✔"

      - name: Simular teste
        run: echo "Testes OK ✔"

      - name: Simular deploy
        run: echo "Deploy OK ✔"
